COPY temp FROM '/home/felipe/Descargas/BlockbusterData.csv' (FORMAT 'csv', DELIMITER ';', NULL '-', HEADER 'true');
-- Tabla Pais 
INSERT 
    INTO PAIS (NOMBRE)
SELECT
    DISTINCT NOMBRE
FROM
    (
    SELECT
        DISTINCT PAIS_CLIENTE AS NOMBRE
    FROM
        temp
    UNION 
    SELECT
        DISTINCT PAIS_EMPLEADO AS NOMBRE
    FROM
        temp
    UNION
    SELECT
        DISTINCT PAIS_TIENDA AS NOMBRE
    FROM
        temp
    ) FOO
WHERE 
    NOMBRE
IS NOT 
    NULL;

-- tABLA CATEGORIA 
INSERT 
    INTO CATEGORIA (NOMBRE)
SELECT 
    DISTINCT CATEGORIA_PELICULA
FROM
    temp
WHERE
    CATEGORIA_PELICULA
IS NOT
    NULL;

-- TABLA ACTOR 
INSERT 
    INTO ACTOR (NOMBRE, APELLIDO)
SELECT 
    DISTINCT
    (SELECT SPLIT_PART(ACTOR_PELICULA, ' ',1)) AS NOMBRE,
    (SELECT SPLIT_PART(ACTOR_PELICULA, ' ',2)) AS APELLIDO
FROM
    temp
WHERE
    ACTOR_PELICULA
IS NOT
    NULL;

-- TABLA IDIOMA 
INSERT 
    INTO IDIOMA (IDIOMA)
SELECT 
    DISTINCT LENGUAJE_PELICULA
FROM
    temp 
WHERE
    LENGUAJE_PELICULA
IS NOT
    NULL;

-- TABLA CIUDAD 
INSERT 
    INTO CIUDAD (CIUDAD, CODIGO_POSTAL, pais_paisid)
SELECT 
    NOMBREC, CODIGO_POSTAL, paisid
FROM
    (
    SELECT
        DISTINCT  CIUDAD_EMPLEADO AS NOMBREC, 
        CODIGO_POSTAL_EMPLEADO AS CODIGO_POSTAL, paisid
    FROM 
        temp
    INNER JOIN 
        PAIS
    ON 
        PAIS_EMPLEADO = NOMBRE
    UNION
    SELECT
        DISTINCT  CIUDAD_TIENDA AS NOMBREC, 
        CODIGO_POSTAL_TIENDA AS CODIGO_POSTAL, paisid
    FROM 
        temp
    INNER JOIN 
        PAIS
    ON 
        PAIS_TIENDA = NOMBRE
    UNION
    SELECT
        DISTINCT  CIUDAD_CLIENTE AS NOMBREC, 
        CODIGO_POSTAL_CLIENTE AS CODIGO_POSTAL, paisid
    FROM 
        temp
    INNER JOIN 
        PAIS
    ON 
        PAIS_CLIENTE = NOMBRE
    ) FOO
WHERE
    NOMBREC
IS NOT
    NULL;


-- TABLA TIENDA 
INSERT 
    INTO TIENDA (DIRECCION, NOMBRE, jefe)
SELECT 
    DISTINCT DIRECCION_TIENDA, NOMBRE_TIENDA, NOMBRE_EMPLEADO 
FROM 
    temp
INNER JOIN 
    CIUDAD
ON 
    CIUDAD_TIENDA = ciudad
WHERE
    NOMBRE_TIENDA
IS NOT
    NULL
ORDER BY
    NOMBRE_TIENDA
ASC;


-- TABLA EMPLEADO 
INSERT
    INTO EMPLEADO (NOMBRE, APELLIDO, DIRECCION, correo, ESTADO, usuario, CONTRASEñA, empleado_tiendaid)
SELECT 
    DISTINCT
    (SELECT SPLIT_PART(NOMBRE_EMPLEADO, ' ',1)) AS NOMBRE,
    (SELECT SPLIT_PART(NOMBRE_EMPLEADO, ' ',2)) AS APELLIDO,
    DIRECCION_EMPLEADO,
    CORREO_EMPLEADO,
    EMPLEADO_ACTIVO,
    USUARIO_EMPLEADO,
    CONTRASENA_EMPLEADO,
    tiendaid
FROM 
    temp
INNER JOIN 
    TIENDA
ON 
    NOMBRE_EMPLEADO = TIENDA.jefe;


-- TABLA CLIENTE 
INSERT
    INTO CLIENTE (NOMBRE, APELLIDO, DIRECCION, correo, registro, ESTADO, cliente_ciudadid, cliente_tiendaid)
SELECT 
    DISTINCT
    (SELECT SPLIT_PART(NOMBRE_CLIENTE, ' ',1)) AS NOMBRE,
    (SELECT SPLIT_PART(NOMBRE_CLIENTE, ' ',2)) AS APELLIDO,
    DIRECCION_CLIENTE,
    CORREO_CLIENTE,
    FECHA_CREACION,
    CLIENTE_ACTIVO,
    ciudadid,
    tiendaid
FROM
    temp
INNER JOIN 
    CIUDAD
ON
    CIUDAD_CLIENTE = CIUDAD.ciudad AND CODIGO_POSTAL_CLIENTE = CIUDAD.CODIGO_POSTAL
INNER JOIN
    TIENDA
ON
    TIENDA_PREFERIDA = TIENDA.NOMBRE
WHERE
    FECHA_CREACION IS NOT NULL AND NOMBRE_CLIENTE IS NOT NULL
ORDER BY
    NOMBRE
ASC;


-- Tabla Pelicula 
INSERT 
    INTO PELICULA (TITULO, DESCRIPCION, lanzamiento, DURACION, cantidad_dias, COSTO, recargo, CLASIFICACION)
SELECT DISTINCT
    NOMBRE_PELICULA, DESCRIPCION_PELICULA, ANO_LANZAMIENTO, DURACION, DIAS_RENTA, COSTO_RENTA, 
    COSTO_POR_DANO, CLASIFICACION 
FROM 
    temp
WHERE
    NOMBRE_PELICULA
IS NOT
    NULL;

-- Tabla Renta 
INSERT
    INTO RENTA (fecha_alquiler, fecha_devolucion, cantidad_pago, renta_clienteid, renta_empleadoid, renta_peliculaid)
SELECT DISTINCT
    FECHA_RENTA, FECHA_RETORNO, MONTO_A_PAGAR, clienteid, empleadoid, peliculaid
FROM 
    temp
INNER JOIN 
    CLIENTE
ON
    NOMBRE_CLIENTE = CLIENTE.NOMBRE || ' ' || CLIENTE.APELLIDO
INNER JOIN
    EMPLEADO 
ON 
    NOMBRE_EMPLEADO = EMPLEADO.NOMBRE || ' ' || EMPLEADO.APELLIDO
INNER JOIN 
    PELICULA
ON
    NOMBRE_PELICULA = TITULO
WHERE
    FECHA_RENTA IS NOT NULL;


-- TABLA INVENTRIO 
INSERT 
    INTO tienda_pelicula (tienda_tiendaid, tienda_peliculaid,cantidad)
SELECT DISTINCT
    tiendaid,
    peliculaid,
    COUNT(*)
FROM
    temp 
INNER JOIN 
    TIENDA
ON 
    TIENDA_PELICULA = TIENDA.NOMBRE
INNER JOIN
    PELICULA
ON
    NOMBRE_PELICULA = PELICULA.TITULO
GROUP BY
    tiendaid, peliculaid;


-- TABLA CATEGORIA-PELICULA 
INSERT 
    INTO categorias_peliculas (categoria_categoriaid, categoria_peliculasid)
SELECT
    DISTINCT categoriaid, peliculaid
FROM 
    temp
INNER JOIN 
    CATEGORIA
ON
    CATEGORIA_PELICULA = CATEGORIA.NOMBRE
INNER JOIN 
    PELICULA
ON
    NOMBRE_PELICULA = PELICULA.TITULO;


-- TABLA ACTOR PELICULA 
INSERT 
    INTO actor_pelicula (actor_actorid, actor_peliculaid)
SELECT 
    DISTINCT actorid, peliculaid 
FROM 
    temp 
INNER JOIN 
    ACTOR
ON
    ACTOR_PELICULA = ACTOR.NOMBRE || ' ' || ACTOR.APELLIDO
INNER JOIN
    PELICULA
ON
    NOMBRE_PELICULA = TITULO;


-- TABLA TRADUCCION 
INSERT
    INTO idioma_pelicula (idioma_idiomaid, idioma_peliculaid)
SELECT 
    DISTINCT idiomaid, peliculaid
FROM
    temp
INNER JOIN
    IDIOMA
ON
    LENGUAJE_PELICULA = IDIOMA.idioma
INNER JOIN 
    PELICULA
ON 
    NOMBRE_PELICULA = TITULO;


SELECT COUNT(*) AS ACTOR FROM ACTOR; 
SELECT COUNT(*) AS ACTOR_PELICULA FROM ACTOR_PELICULA; 
SELECT COUNT(*) AS CATEGORIA FROM CATEGORIA; 
SELECT COUNT(*) AS categorias_peliculas FROM categorias_peliculas; 
SELECT COUNT(*) AS CIUDAD FROM CIUDAD; 
SELECT COUNT(*) AS CLIENTE FROM CLIENTE; 
SELECT COUNT(*) AS EMPLEADO FROM EMPLEADO; 
SELECT COUNT(*) AS IDIOMA FROM IDIOMA; 
SELECT COUNT(*) AS TIENDA_PELICULA FROM TIENDA_PELICULA; 
SELECT COUNT(*) AS PAIS FROM PAIS; 
SELECT COUNT(*) AS PELICULA FROM PELICULA; 
SELECT COUNT(*) AS RENTA FROM RENTA; 
SELECT COUNT(*) AS temp FROM temp; 
SELECT COUNT(*) AS TIENDA FROM TIENDA; 
